remote_theme: "mmistakes/minimal-mistakes"
title: diskover
description: Elasticsearch file system crawler and storage analytics.
show_downloads: true
google_analytics: UA-98866026-1
plugins:
  - jekyll-remote-theme
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
