remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "diskover"
title_separator          : "-"
name                     : "Chris Park"
description              : "Elasticsearch file system crawler and storage analytics."
url                      : https://shirosaidev.github.io
baseurl                  : "/diskover"
repository               : "shirosaidev/diskover"
title                    : "diskover"
show_downloads           : true
google_analytics:        : UA-98866026-1

plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
