remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "diskover"
title_separator          : "-"
name                     : "shirosaidev"
description              : "Elasticsearch file system crawler and storage analytics."
url                      : https://shirosaidev.github.io
baseurl                  : "/diskover"
repository               : "shirosaidev/diskover"
show_downloads           : true

# Analytics
analytics:
  provider               : google
  google:
    tracking_id          : UA-98866026-1

plugins:
  - jekyll-remote-theme
include: ["_pages"]
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true
